/* JAXON — engineer. Portrait: assets/crew/M_2.png. (work in progress) */
CrewSprites.register({
    id: 'jaxon',
    name: 'Jaxon',
    role: 'Engineer',
    portrait: '../../assets/crew/M_2.png',
    signature: 'Dark hair slicked back, grey at the temple; amber light down the front of his face; stubble; dark work jacket.',
    idle: 'crossed',
    palette: {
        hair: ['#0e0f11', '#2a2e33', '#4f565e', '#9ca3a9'],
        skin: ['#552c1a', '#a8643c', '#cf8653'],
        glow: ['#6e3410', '#e98a2c', '#ffc56e'],
        stub: ['#3a2a22', '#6a5246', '#8a7468'],
        eye: ['#1a2430', '#5f7c92', '#b9d0de'],
        suit: ['#181715', '#34322e', '#4f4b45'],
        pants: ['#121417', '#2a2f35', '#3f464e'],
        belt: ['#1e140c', '#4b3322', '#6e4d33'],
        boot: ['#0e0c0a', '#231e1a', '#3c342d'],
    },
    keys: {
        1: 'hair:0', 2: 'hair:1', 3: 'hair:2', 4: 'hair:3',
        k: 'skin:0', s: 'skin:1', S: 'skin:2', e: 'eye:1',
        g: 'glow:0', a: 'glow:1', A: 'glow:2',
        t: 'stub:0', u: 'stub:1',
        b: 'suit:0', n: 'suit:1', N: 'suit:2',
        d: 'belt:0', l: 'belt:1', L: 'belt:2',
    },
    blink: ['e', 's'],
    head: {
        side: { anchor: [3, 6], map: [
            '..2333a.',
            '.1244SSa',
            '124s1s1a',
            '12kseseA',
            '.1kssksA',
            '..kuukua',
            '..bnnn..',
        ] },
        down: { anchor: [3, 6], map: [
            '..2333..',
            '.123333a',
            '1244SSSa',
            '12k41s1a',
            '.1kssksA',
            '..kuuua.',
            '..bnnn..',
        ] },
        back: { anchor: [4, 6], map: [
            '..23332..',
            '.2333332.',
            '.4222224.',
            'k4122214k',
            '.1122211.',
            '..ksssk..',
            '..bnnnb..',
        ] },
    },
    torso: {
        side: { spine: 3, squash: 3, map: [
            '.nnnNNN',
            'bnnnnNN',
            'bnnnnNN',
            'bbnnnnN',
            'bbnnnnn',
            'dlllllL',
        ] },
        back: { spine: 4, squash: 3, map: [
            '.nnnnnnn.',
            'bnnnnnnnb',
            'bnnnnnnnb',
            '.bnnnnnb.',
            '.bnnnnnb.',
            '.dllllld.',
        ] },
    },
    backShoulder: 4,
    limbs: { arm: 'suit', hand: 'skin', cuff: 'skin', leg: 'pants', foot: 'boot', bootRows: 2, rim: true },
});
